name: stripe_payment
description: A Flutter plugin to integrate the stripe libraries for iOS and Android. Supports Apple / Google Pay, SCA, PSD2 and much more.
version: 1.0.9
homepage: https://github.com/jonasbark/flutter_stripe_payment

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  json_annotation: ^4.0.0 # built ^3.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  json_serializable: ^4.0.0 # built with ^3.5.1

flutter:
  plugin:
    platforms:
      android:
        package: de.jonasbark.stripepayment
        pluginClass: StripePaymentPlugin
      ios:
        pluginClass: StripePaymentPlugin
